- source/includes/usage-examples/code-snippets/command.go
- source/usage-examples.txt
- source/usage-examples/command.txt
Added Usage Examples > Run a Command
https://jira.mongodb.org/browse/DOCSP-13866
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13866-CommandUsageExample/usage-examples/command/
> DOCSP-13866 run a command usage example

- source/includes/usage-examples/code-snippets/watch.go
- source/usage-examples.txt
- source/usage-examples/watch.txt
Added Usage Examples > Watch for Changes page
https://jira.mongodb.org/browse/DOCSP-13867
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13867-WatchUsageExample/usage-examples/watch/
> DOCSP-13867 watch usage example

- snooty.toml
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/usage-examples/bulkWrite.txt
- source/usage-examples/command.txt
- source/usage-examples/count.txt
- source/usage-examples/distinct.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/watch.txt
Cleaning up our constants.
NA
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=612e4a987dcf0129306a16fc
https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/fix-example-constant/
> rename and clean up constants

- source/includes/fundamentals/code-snippets/srv.go
- source/includes/quick-start/main.go
This replaces the use of 'global' contexts with unique contexts for each function call.
https://jira.mongodb.org/browse/DOCSP-18437
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=612fd9377dcf012930c553f9
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18437/quick-start/#query-your-mongodb-cluster-from-your-application
> use unique contexts

- source/includes/usage-examples/code-snippets/bulk.go
- source/includes/usage-examples/code-snippets/command.go
- source/includes/usage-examples/code-snippets/count.go
- source/includes/usage-examples/code-snippets/deleteMany.go
- source/includes/usage-examples/code-snippets/deleteOne.go
- source/includes/usage-examples/code-snippets/distinct.go
- source/includes/usage-examples/code-snippets/insertMany.go
- source/includes/usage-examples/code-snippets/insertOne.go
- source/includes/usage-examples/code-snippets/replace.go
- source/includes/usage-examples/code-snippets/updateMany.go
- source/includes/usage-examples/code-snippets/updateOne.go
Updated all usage examples code:
- ran go fmt on all usage example code
- added what output should be for each file
https://jira.mongodb.org/browse/DOCSP-18443
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=612fc86c7dcf012930c15c4f
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18443-RunnableCode/
> DOCSP-18443 usage examples code

- source/fundamentals.txt
- source/fundamentals/crud/write-operations/insert.txt
This PR subsumes https://github.com/mongodb/docs-golang/pull/19 and addressed most of the feedback there.
https://jira.mongodb.org/browse/DOCSP-13841
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6127b6ff7dcf012930f3cc07
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13841/fundamentals/crud/write-operations/insert/
- It is *NOT*. The RST errors are from another file that will be corrected in a separate PR.
> Insert Fundamentals

- source/issues-and-help.txt
Updated the testing section to link to the go-driver README.md file 
https://jira.mongodb.org/browse/DOCSP-DOCSP-18733
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61436198c608bec57fc60b45
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18733/issues-and-help/
> DOCSP-18733 issues and help

- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/fundamentals/crud/write-operations/insert.txt
Updated the available CRUD pages to:
- say "function" instead of "method"
- provide all links at the bottom of the page (Additional Information section)
- show properties in a table (change a doc page)
- define what each method does in the overview (insert page)
- not show Example heading in the sidebar toc
https://jira.mongodb.org/browse/DOCSP-18739
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6143a6fcc608bec57fdee196
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18739/fundamentals/crud/write-operations/change-a-document/
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18739/fundamentals/crud/write-operations/insert/
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18739/fun …
> DOCSP-18739

- source/fundamentals/connection.txt
- source/includes/quick-start/atlas-setup.rst
- source/usage-examples.txt
Updated the connection guide to have a "Other Ways to Connect to MongoDB" section. This separates the code we present right before.
Also, I updated the doc reference in the usage example landing page since it gave me a snooty error.
https://jira.mongodb.org/browse/DOCSP-18734
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6143afb3c608bec57fe1facf
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18734/fundamentals/connection/
> DOCSP-18734 connection guide

- source/fundamentals.txt
- source/index.txt
Updated the landing page to reflect what was done for the [Java page](https://docs.mongodb.com/drivers/java/sync/current/).
https://jira.mongodb.org/browse/DOCSP-18691
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6143cbd9c608bec57febcf9b
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18691/
> DOCSP-18691

- source/fundamentals/crud/write-operations/insert.txt
Changed "A Note About _id" to "Use ``_id`` as a Unique Index"
Other titles I considered but are unsure if better:
- _id as a Unique Index
- Managing _id
- Decide How To Generate _id
- Ways to Generate _id
Alternatively, I can put the entire section in an important or note admonition.
https://jira.mongodb.org/browse/DOCSP-18738
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61449b29c608bec57f21e7c7
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18738/fundamentals/crud/write-operations/insert/
> DOCSP-18738

- source/fundamentals/collations.txt
- source/fundamentals/gridfs.txt
- source/fundamentals/logging.txt
- source/fundamentals/monitoring.txt
This removes blanks to clean up deploy errors that do not show up in staging builds.
na
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6144c00ac608bec57f2cc34e
https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/cleanup-blanks/
> removing blanks

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/limit.txt
- source/fundamentals/crud/read-operations/project.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/includes/fundamentals/code-snippets/CRUD/projection.go
Added the Fundamentals > CRUD > Read Operations > Specify Which Fields to Return page
I also: 
- simplified the Additional Information section on the Skip and Limit page
- added a comment for the aggregation page to each existing read operations page
- updated the Sample Data opening sentence on each read operations page
https://jira.mongodb.org/browse/DOCSP-13838
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61689aad8670bd2731884c41
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13838-CRUDProjection/fundamentals/crud/read-operations/project/
> DOCSP-13838 crud projection

- source/fundamentals/crud.txt
- source/fundamentals/crud/compound-operations.txt
- source/fundamentals/crud/query-document.txt
- source/fundamentals/crud/read-operations/limit.txt
- source/fundamentals/crud/read-operations/project.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/upsert.txt
- source/includes/fundamentals/code-snippets/CRUD/query.go
- source/includes/fundamentals/tea-sample-data-ending.rst
- source/includes/fundamentals/truncated-id.rst
Added Fundamentals > CRUD > Specify a Query
https://jira.mongodb.org/browse/DOCSP-13847
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=616f0d70c13055282dad4213
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13847-CRUDQuery/fundamentals/crud/query-document/
> DOCSP-13847 specify a query

- source/index.txt
https://jira.mongodb.org/browse/DOCSP-20493
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=61f022b5bcf82347e5c57f90
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-20493/
> (DOCSP-20493) standardize driver intros: golang

- source/index.txt
https://jira.mongodb.org/browse/DOCSP-20534
**Paste your workerpool job link here**
https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/NNNNNNNNNNN/
> (DOCSP-20534) Backport standardized driver intro

- .github/pull_request_template.md
- README.rst
Updates to README and PR template
>  community update

- source/fundamentals/bson.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-221918>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-221918/>
> DOCSP-221918 fix broken link

- snooty.toml
Updating API docs version
JIRA - <https://jira.mongodb.org/browse/DOCSP-21852>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-21852/#api>
> DOCSP-21852 Update API docs version v1.8

- source/fundamentals/bson.txt
- source/fundamentals/crud/compound-operations.txt
- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/distinct.txt
- source/fundamentals/crud/read-operations/limit.txt
- source/fundamentals/crud/read-operations/project.txt
- source/fundamentals/crud/read-operations/query-document.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/fundamentals/crud/read-operations/text.txt
- source/fundamentals/crud/write-operations/bulk.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/embedded-arrays.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/upsert.txt
Updated code blocks with a specified "expected output" to use io-code-block.
This change applies to most of the pages in the "Fundamentals" section.
JIRA - <https://jira.mongodb.org/browse/DOCSP-21850>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-21850/fundamentals/crud/read-operations/query-document/>
> DOCSP-21850

- source/fundamentals.txt
- source/fundamentals/aggregation.txt
- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/limit.txt
- source/fundamentals/crud/read-operations/project.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/fundamentals/crud/read-operations/text.txt
- source/includes/fundamentals-sections.rst
- source/includes/fundamentals/code-snippets/aggregation.go
Added the Fundamentals > Aggregation page.
JIRA - <https://jira.mongodb.org/browse/DOCSP-19063>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19063/fundamentals/aggregation/>
> DOCSP-19063 aggregation

- source/fundamentals/aggregation.txt
- source/fundamentals/bson.txt
- source/fundamentals/crud/compound-operations.txt
- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/distinct.txt
- source/fundamentals/crud/read-operations/limit.txt
- source/fundamentals/crud/read-operations/project.txt
- source/fundamentals/crud/read-operations/query-document.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/fundamentals/crud/read-operations/text.txt
- source/fundamentals/crud/write-operations/bulk.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/embedded-arrays.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/upsert.txt
- source/fundamentals/time-series.txt
- source/quick-reference.txt
Updated all output blocks to not be visible and to have its language as `none`.
JIRA - <https://jira.mongodb.org/browse/DOCSP-22623>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-22623/>
> DOCSP-22623 output block updates

- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-23036>
Staging - <https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-23036/>
> (DOCSP-23036) Bump Go Version

- snooty.toml
- source/fundamentals.txt
- source/fundamentals/indexes.txt
- source/includes/fundamentals-sections.rst
- source/includes/fundamentals/code-snippets/indexes.go
- source/index.txt
- source/quick-reference.txt
Added the Fundamentals > Indexes page -- this also documents clustered indexes (I closed this ticket previously since the tasks overlapped).
JIRA - <https://jira.mongodb.org/browse/DOCSP-13850>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13850/fundamentals/indexes/>
> DOCSP-13850 indexes

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/watch.txt
- source/includes/fundamentals/automatic-db-coll-creation.rst
- source/usage-examples/watch.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-18456>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18456-change-stream-page/fundamentals/crud/read-operations/watch/>
> DOCSP-18456: adding a change stream page

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/watch.txt
- source/includes/fundamentals/automatic-db-coll-creation.rst
- source/usage-examples/watch.txt
* DOCSP-18456: adding a change stream page
* fixing TOC
* code example typo
* wording fix
* more task oriented structure
* fixed punctuation
(cherry picked from commit 2ee7da991cfe7ea414cfe392258baa9a3059fed4)
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.9/>
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62ea8790230aeb802e66d6c7
> DOCSP-18456: Change stream page v1.9 (#113)

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/watch.txt
- source/includes/fundamentals/automatic-db-coll-creation.rst
- source/usage-examples/watch.txt
* DOCSP-18456: adding a change stream page
* fixing TOC
* code example typo
* wording fix
* more task oriented structure
* fixed punctuation
(cherry picked from commit 2ee7da991cfe7ea414cfe392258baa9a3059fed4)
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.7/>
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62ea88b6230aeb802e6701f8
> DOCSP-18456: Change stream page v1.7 (#113)

- source/fundamentals/bson.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-24173>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-24173/fundamentals/bson/>
> DOCSP-24173 Remove ellipses from code blocks

- source/fundamentals/bson.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-24173>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.7/fundamentals/bson/>
> removing elipses from runnable code (#120)

- .github/workflows/copy-compat-to-docs-shared.yml
- source/compatibility.txt
- source/includes/language-compatibility-table-go.rst
- source/includes/mongodb-compatibility-table-go.rst
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/docsp-24483/compatibility/
- [] Did you run a spell-check?
- [] Did you run a grammar-check?
> Add workflow action / update compatibility.txt

- source/compatibility.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.10/compatibility/
> Add table legend / link to About page [v1.10]

- source/compatibility.txt
(cherry picked from commit d78f2d97097799ad7b4030ef2f7ce11740195bd5)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.8/compatibility/
> add table legend and link to About page [v1.8 backport]

- source/compatibility.txt
(cherry picked from commit d78f2d97097799ad7b4030ef2f7ce11740195bd5)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.7-docsp-24483/compatibility/
> add table legend and link to About page [v1.7 backport]

- source/compatibility.txt
(cherry picked from commit d78f2d97097799ad7b4030ef2f7ce11740195bd5)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.9-backport/compatibility/
> add table legend and link to About page [v1.9 backport]

- source/compatibility.txt
- Added "On this Page" widget
- Made heading levels consistent with other repos
- Changed "version(s)" to "version" per style guide (and other repos)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/docsp-24760/compatibility/
> [DOCSP-24760] Add "On this Page" to Compat Page

- snooty.toml
- source/fundamentals.txt
- source/fundamentals/geo.txt
- source/includes/fundamentals-sections.rst
Work with Geospatial Data page for Go.
[JIRA](https://jira.mongodb.org/browse/DOCSP-13839)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13839-geospatial-search-page/fundamentals/geo/)
> geospatial page

- source/compatibility.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.10/compatibility/
> [DOCSP-24760] V1.10 backport

- source/compatibility.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.9/compatibility/
> [DOCSP-24760] V1.9 backport

- source/compatibility.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.8/compatibility/
> [DOCSP-24760] V1.8 backport

- source/compatibility.txt
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.7/compatibility/
> [DOCSP-24760] V1.7 backport

- source/usage-examples.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/cherry-pick-1.8/usage-examples/)
> remove redundant connection guide link (#149)

- source/fundamentals/collations.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/quick-reference.txt
- source/usage-examples/deleteMany.txt
- source/usage-examples/find-operations.txt
- source/usage-examples/find.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/updateMany.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-25568>
Staging:
[Ticket-reported instance](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25568-link-fix/fundamentals/crud/read-operations/retrieve/#additional-information)
[Delete Many reference](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25568-link-fix/usage-examples/deleteMany/#expected-result)
[Quick Reference reference](https://www.mongodb.com/docs/drivers/node/current/quick-reference/)
[Find Operations reference](https://www.mongodb.com/docs/drivers/node/current/usage-examples/find-operations/)
[Update Multiple reference](https://docs-mongodbcom-staging.corp.mongodb.com/golang/doc …
> DOCSP-25568: fix links

- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-25685>
Staging -https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25685-v1.10.3-update/
> DOCSP-25685: patch release for v1.10.3

- source/includes/usage-examples/code-snippets/find.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-25839>
> DOCSP-25839: initialize struct

- source/fundamentals/crud.txt
- source/fundamentals/crud/write-read-pref.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-13849
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13849-read-write-concern/fundamentals/crud/write-read-pref/
> DOCSP-13849: Modify CRUD op execution

- source/includes/usage-examples/code-snippets/find.go
- source/usage-examples/find.txt
- source/usage-examples/findOne-output.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-25873>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25873-struct-tagging-find/usage-examples/find/>
> DOCSP-25873 Add Restaurant Structs to Find Usage Example 

- source/includes/usage-examples/code-snippets/find.go
- source/usage-examples/find.txt
Ports #165 to v1.10
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25873-struct-tagging-find-v1.10/usage-examples/find/>
> DOCSP-25873 v1.10 backport

- source/includes/usage-examples/code-snippets/find.go
- source/usage-examples/find.txt
Port #165 to v1.9
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25873-struct-tagging-find-v1.9/usage-examples/find/>
> DOCSP-25873 v1.9 backport

- source/includes/usage-examples/code-snippets/find.go
- source/usage-examples/find.txt
Port #165 to v1.8
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25873-struct-tagging-find-v1.8/usage-examples/find/>
> DOCSP-25873 backport v1.8

- source/includes/usage-examples/code-snippets/find.go
- source/usage-examples/find.txt
Ports #165 to v1.7
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25873-struct-tagging-find-v1.7/usage-examples/find/
> DOCSP-25873 v1.7 backport

- source/includes/usage-examples/code-snippets/findOne.go
- source/usage-examples/findOne.txt
Port #164 to v1.8
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25874-struct-tagging-findone-v1.8/usage-examples/findOne/>
> DOCSP-25874 backport v1.8

- source/includes/usage-examples/code-snippets/findOne.go
- source/usage-examples/findOne.txt
Port #164 to v1.9
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25874-struct-tagging-findone-v1.9/usage-examples/findOne/>
> DOCSP-25874 backport v1.9

- source/includes/usage-examples/code-snippets/findOne.go
- source/usage-examples/findOne.txt
Port #164 to v1.10
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25874-struct-tagging-findone-v1.10/usage-examples/findOne/>
> DOCSP-25874 backport v1.10

- source/fundamentals/crud.txt
- source/fundamentals/crud/run-command.txt
- source/includes/fundamentals/code-snippets/CRUD/runCommand.go
JIRA - https://jira.mongodb.org/browse/DOCSP-18237
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18237-runCommand/fundamentals/crud/run-command/
> DOCSP-18237: run a command

- source/fundamentals/crud.txt
- source/fundamentals/crud/run-command.txt
- source/fundamentals/crud/write-read-pref.txt
- source/includes/fundamentals/code-snippets/CRUD/runCommand.go
Ports https://github.com/mongodb/docs-golang/pull/176 to v1.10.
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.10/fundamentals/crud/run-command/
> DOCSP-18237 run a command Backport #176 to v1.10

- source/fundamentals/crud.txt
- source/fundamentals/crud/run-command.txt
- source/fundamentals/crud/write-read-pref.txt
- source/includes/fundamentals/code-snippets/CRUD/runCommand.go
Ports https://github.com/mongodb/docs-golang/pull/176 to v1.8.
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.8/fundamentals/crud/run-command/
> DOCSP-18237 run a command Backport #176 to v1.8

- source/fundamentals/crud.txt
- source/fundamentals/crud/run-command.txt
- source/fundamentals/crud/write-read-pref.txt
- source/includes/fundamentals/code-snippets/CRUD/runCommand.go
Ports https://github.com/mongodb/docs-golang/pull/176 to v1.7.
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.7/fundamentals/crud/run-command/
> DOCSP-18237 run a command Backport #176 to v1.7

- snooty.toml
- source/includes/language-compatibility-table-go.rst
Bumps min go version
JIRA - <https://jira.mongodb.org/browse/DOCSP-26180>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26180/compatibility/#language-compatibility)
> (DOCSP-26180) Bump Min Go Version

- source/index.txt
- source/whats-new.txt
Port #185 to v1.10
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19057-whats-new-v1.10/whats-new/>
> DOCSP-19057 v1.10 Backport

- source/whats-new.txt
Port https://github.com/mongodb/docs-golang/pull/185 to v1.7
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19057-whats-new-v1.7/whats-new/
> DOCSP-19057 v1.7 backport

- source/includes/usage-examples/code-snippets/insertMany.go
- source/usage-examples/insertMany.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-26413>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26413-update-insert-many-example-structs/usage-examples/insertMany/>
> DOCSP-26413 Update Insert Many Usage Example Structs

- source/includes/usage-examples/code-snippets/insertMany.go
- source/includes/usage-examples/code-snippets/insertOne.go
- source/includes/usage-examples/code-snippets/replace.go
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-26414>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26414-replace-a-doc-structs/usage-examples/replaceOne/>
Also incorporating feedback about shortened code samples/fields to [Insert a Document](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26414-replace-a-doc-structs/usage-examples/insertOne/) and[ Insert Multiple Documents](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26414-replace-a-doc-structs/usage-examples/insertMany/) pages.
> DOCSP-26414 Update "Replace a Document" Usage Example with Document Structs

- source/fundamentals/connection.txt
- source/fundamentals/context.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26194
Staging:
Context page: https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26194-csot/fundamentals/context/#single-timeout-setting
Connection guide (connection options): https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26194-csot/fundamentals/connection/#connection-options
> DOCSP-26194: CSOT

- .github/workflows/check-autobuilder.yml
- source/fundamentals/connection.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-25508
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25508-retry-logic/fundamentals/connection/#single-timeout-setting (just the note)
> DOCSP-25508: retry logic

- source/includes/usage-examples/code-snippets/watch.go
- source/usage-examples/watch.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-26777>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26777-fix-watch-for-changes-new-example/usage-examples/watch/>
> DOCSP-26777 Update Watch for Changes Usage Example to Match w/ Find Example

- source/fundamentals.txt
- source/fundamentals/monitoring.txt
- source/includes/fundamentals-sections.rst
JIRA - https://jira.mongodb.org/browse/DOCSP-19060
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19060-monitoring/fundamentals/monitoring/
> DOCSP-19060: monitoring

- source/fundamentals/aggregation.txt
- source/includes/fundamentals/code-snippets/aggregation.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26417
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26417-aggregation-struct/fundamentals/aggregation/
> DOCSP-26417: use struct in aggregation pg

- source/fundamentals/crud/read-operations/query-document.txt
- source/includes/fundamentals/code-snippets/CRUD/query.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26434
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26434-struct-specify-query/fundamentals/crud/read-operations/query-document/#std-label-golang-query-document
> DOCSP-26434: use struct in specify query pg

- source/fundamentals/crud/compound-operations.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26830
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/docsp-26830-find-and-update/fundamentals/crud/compound-operations/
> DOCSP-26830 - Clarify compound operations

- source/fundamentals/crud/read-operations/retrieve.txt
- source/includes/fundamentals/code-snippets/CRUD/retrieve.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26436
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26436-struct-retrieve-data/fundamentals/crud/read-operations/retrieve/
> DOCSP-26436: use struct in retrieve data pg

- source/fundamentals/crud/read-operations/distinct.txt
- source/includes/fundamentals/code-snippets/CRUD/distinctValues.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26438
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26438-struct-distinct/fundamentals/crud/read-operations/distinct/
> DOCSP-26438: use struct in distinct pg

- source/fundamentals/crud/read-operations/skip.txt
- source/includes/fundamentals/code-snippets/CRUD/skip.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26440
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26440-struct-skip/fundamentals/crud/read-operations/skip/
> DOCSP-26440: use struct on skip pg

- source/fundamentals/crud/read-operations/project.txt
- source/includes/fundamentals/code-snippets/CRUD/projection.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26442
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26442-struct-project/fundamentals/crud/read-operations/project/
> DOCSP-26442: use struct in projection pg

- source/fundamentals/crud/compound-operations.txt
- source/fundamentals/encrypt-fields.txt
- source/includes/fundamentals/code-snippets/CRUD/compoundOperations.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26452
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26452-struct-compound/fundamentals/crud/compound-operations/
> DOCSP-26452: use struct in compound ops

- source/fundamentals/crud/run-command.txt
- source/includes/fundamentals/code-snippets/CRUD/runCommand.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26229
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26229-improve-runcmd/fundamentals/crud/run-command/
See #178 for comments that this PR addresses.
> DOCSP-26229: improve-runcommand

- source/faq.txt
- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-13871
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13871-FAQ/faq/
> DOCSP-13871: FAQ page

- source/fundamentals/crud/read-operations/watch.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-22507
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-22507-changestream-pre-image/fundamentals/crud/read-operations/watch/#pre--and-post-images
> DOCSP-22507: changestream pre and post images

- source/fundamentals/connection.txt
- source/includes/fundamentals/code-snippets/srv.go
JIRA - https://jira.mongodb.org/browse/DOCSP-27920
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-27920-quickstart-stable-api/fundamentals/connection/
**Note: I replaced the connection string with a placeholder to align with guidance from [this document](https://docs.google.com/document/d/1m-mEe8qH_rIAAiekC8Ehr4qjpSY-BOOapJAyizsIoHM/edit#)**
> DOCSP-27920: atlas connection snippet w stableapi

- source/fundamentals/connection.txt
- source/includes/fundamentals/code-snippets/srv.go
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/CC-feedback-27920/fundamentals/connection/#connection-example
#238
> Respond to CC feedback on #238

- source/fundamentals/connection.txt
- source/includes/fundamentals/code-snippets/srv.go
(cherry picked from commit a389d042923eaca77641672eae89840f8f1b504a)
Changes that were still not addressed in #238 and #239 
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/further-changes-27920/fundamentals/connection/#connection-example
> changes following from C#

- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-28681
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-28681-version-1-11-3/whats-new/#what-s-new-in-1.11
- [n/a] Are all the links working?
> DOCSP-28681: version update + retraction notice

- source/includes/fundamentals/code-snippets/srv.go
JIRA - [DOCSP-27920](https://jira.mongodb.org/browse/DOCSP-27920)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/stable-api-updates-cleanup/fundamentals/connection/#connection-example
> match convention

- source/fundamentals/crud/read-operations/count.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27258
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-27258-coundDocuments-collScan/fundamentals/crud/read-operations/count/#accurate-count
> DOCSP-27258 countDocuments collScan note

- source/fundamentals/auth.txt
- source/includes/fundamentals/code-snippets/authentication/aws-connection-string-session-token.go
- source/includes/fundamentals/code-snippets/authentication/aws-connection-string.go
- source/includes/fundamentals/code-snippets/authentication/aws-environment-variables.go
JIRA - https://jira.mongodb.org/browse/DOCSP-28794
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-28794-aws-eks/fundamentals/auth/#mongodb-aws
> DOCSP-28794 AWS Auth Mechanisms

- source/index.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29626
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-29626-move-WN/#what-s-new and see left nav
> DOCSP-29626: move whats new in nav

- config/redirects
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/changestream.txt
- source/quick-reference.txt
- source/usage-examples.txt
- source/usage-examples/changestream.txt
JIRA - [DOCSP-29782](https://jira.mongodb.org/browse/DOCSP-29782)
Staging: [Usage Example](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-29782-watch-google-results/usage-examples/changestream/) // [Fundamentals Page](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-29782-watch-google-results/fundamentals/crud/read-operations/changestream/)
> DOCSP-29782: change how google sees change stream pages

- source/connection-troubleshooting.txt
- source/faq.txt
- source/fundamentals/connection.txt
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-29489>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-29489/connection-troubleshooting/#std-label-golang-connection-troubleshooting>
> Added Connection Troubleshooting guide

- source/fundamentals/geo.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30083>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-30083-fix-geospatial-typo/fundamentals/geo/#geospatial-indexes>
> DOCSP-30083 : fix geospatial typo

- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/query-document.txt
- source/fundamentals/crud/read-operations/text.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/includes/fundamentals-sections.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-30082?workflowName=Documentation+Workflow&stepId=4>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-30082-v1.11-doc-to-ref/>
> DOCSP-30082-v1.11-doc-to-ref

- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/query-document.txt
- source/fundamentals/crud/read-operations/text.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/includes/fundamentals-sections.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-30082?workflowName=Documentation+Workflow&stepId=4>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.10/>
> DOCSP-30082 v1.10 doc to ref

- source/fundamentals.txt
- source/fundamentals/geo.txt
- source/includes/fundamentals-sections.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-30692>
Staging:
- [Fundamentals section of index](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.10/#fundamentals)
- [geo page](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.10/fundamentals/geo/)
- check left hand nav
> DOCSP-30692: backport geo pg

- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/query-document.txt
- source/fundamentals/crud/read-operations/text.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/includes/fundamentals-sections.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-30082>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-30082-v1.9-doc-to-ref/>
> DOCSP-30082: v1.9 doc to ref

- source/fundamentals/crud/write-read-pref.txt
- source/fundamentals/transactions.txt
- source/includes/fundamentals/code-snippets/transaction.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-30748>
Staging:
- [Write concern guide](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-30748-wc-api-streamline/fundamentals/crud/write-read-pref/#write-concern)
- [transactions pg example](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-30748-wc-api-streamline/fundamentals/transactions/#example)
> DOCSP-30748: WriteConcern api streamline

- config/redirects
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/modify.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-31825>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-31825-update-titles/fundamentals/crud/write-operations/modify/>
<https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-31825-update-titles/fundamentals/crud/write-operations/delete/>
Redirects - 
Redirect 301 /docs/drivers/go/1.7/fundamentals/crud/write-operations/change-a-document/ https://www.mongodb.com/docs/drivers/go/1.7/fundamentals/crud/write-operations/modify/
Redirect 301 /docs/drivers/go/1.8/fundamentals/crud/write-operations/change-a-document/ https://www.mongodb.com/docs/drivers/go/1.8/fundamentals/crud/write-operations/m …
> DOCSP-31825: Update titles

- config/redirects
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/modify.txt
* DOCSP-31825: updated page titles
* build
* build
* fixing version range
* fixing headers and typos
* redirects typo
(cherry picked from commit bc91936c0402eca8b2099a9305d1a7f1000ff32d)
JIRA - <https://jira.mongodb.org/browse/DOCSP-31825>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.10/fundamentals/crud/write-operations/#std-label-golang-crud-write-operations>
> DOCSP-31825: Update titles (#283)

- source/facets.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-32483>
Hi @mongoKart - here's the facet.toml file for the Go Driver repo.  Please merge if it looks good!
Thanks!
Sarah
> DOCSP-32483 programmatic tagging script for go driver repo

- source/fundamentals/connection.txt
- source/index.txt
Hi @caitlindavey & @mongoKart - 
Here are the two manually tagged files for docs-golang from the top 250.  Please merge if everything looks good!
Thank you!
Sarah
JIRA - <https://jira.mongodb.org/browse/DOCSP-27817>
> DOCSP-27817 manual tagging on docs-golang repo

- source/fundamentals/connection.txt
- source/includes/fact-environments.rst
- source/index.txt
JIRA 
- <https://jira.mongodb.org/browse/DOCSP-32298>
- <https://jira.mongodb.org/browse/DOCSP-32268>
Landing Staging - <https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-32298/>
Connection Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-32298/fundamentals/connection/>
Build - <https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65130be2492df295cff9e1b2>
> DOCSP-32298 adds compatibility info to landing and connection page

- source/fundamentals/crud/write-read-pref.txt
JIRA - https://jira.mongodb.org/browse/DOCS-16418
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/golang/DOCS-16418-readwrite-concern/fundamentals/crud/write-read-pref/
> DOCS-16418 Remove Query Level bullet

- source/fundamentals/crud/write-read-pref.txt
(cherry picked from commit d214604c905f37b8c0ba9e81d8242774b73faead)
> remove inaccurate bullet (#299)

- source/fundamentals/bson.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33481>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/golang/DOCSP-33481-bson-options-example/fundamentals/bson/>
> DOCSP-33481: Update BSONOptions Example

- source/fundamentals/crud/write-operations/upsert.txt
- source/fundamentals/crud/write-read-pref.txt
- source/fundamentals/encrypt-fields.txt
- source/fundamentals/enterprise-auth.txt
- source/fundamentals/geo.txt
- source/fundamentals/gridfs.txt
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/taxonomy-tagging/
> Add taxonomy to some go pages

- source/fundamentals/crud/read-operations/distinct.txt
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/golang/distinct-tagging/fundamentals/crud/read-operations/distinct/>
> Distinct guide tagging

- source/fundamentals/crud/read-operations/limit.txt
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/golang/limit-tagging/fundamentals/crud/read-operations/limit/>
> Limit guide tagging

- source/fundamentals/crud/read-operations/project.txt
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/golang/project-tagging/fundamentals/crud/read-operations/project/>
> Project guide tagging

- snooty.toml
JIRA - https://jira.mongodb.org/browse/DOCSP-34284 (Note: This PR is Go update only.)
Staging - https://preview-mongodbmongokart.gatsbyjs.io/golang/docsp-34284-version-update/
> docsp-34284 - patch version update

- config/redirects
- snooty.toml
- source/fundamentals.txt
- source/fundamentals/connections.txt
- source/fundamentals/connections/connection-guide.txt
- source/fundamentals/connections/network-compression.txt
- source/fundamentals/connections/tls.txt
- source/includes/fundamentals-sections.rst
- source/includes/fundamentals/code-snippets/tls.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-34062>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34062-tls/fundamentals/connections/tls/
Redirects test:
```
Redirect 301 /docs/drivers/go/v1.7/fundamentals/connection/ https://www.mongodb.com/docs/drivers/go/v1.7/fundamentals/connections/connection-guide
Redirect 301 /docs/drivers/go/v1.8/fundamentals/connection/ https://www.mongodb.com/docs/drivers/go/v1.8/fundamentals/connections/connection-guide
Redirect 301 /docs/drivers/go/v1.9/fundamentals/connection/ https://www.mongodb.com/docs/drivers/go/v1.9/fundamentals/connections/connection-guide
Redirect 301 /docs/drivers/go/v1.10/fundamentals/connection/ …
```
> DOCSP-34062: tls

- source/usage-examples/facets.toml
Hey @ccho-mongodb - here's the docs-golang new facet.toml file.
JIRA - <https://jira.mongodb.org/browse/DOCSP-31343>
Staging - <https://preview-mongodbsarahemlin.gatsbyjs.io/golang/DOCSP-31343/>
> DOCSP-31343 add usage examples facet.toml file

- source/includes/fundamentals/code-snippets/CRUD/bulkOps.go
- source/includes/usage-examples/code-snippets/bulk.go
- source/includes/usage-examples/code-snippets/command.go
- source/includes/usage-examples/code-snippets/count.go
- source/includes/usage-examples/code-snippets/deleteMany.go
- source/usage-examples/bulkWrite.txt
- source/usage-examples/command.txt
- source/usage-examples/count.txt
- source/usage-examples/deleteMany.txt
Staging:
[bulk fundamentals](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-2/fundamentals/crud/write-operations/bulk/)
[bulk UE](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-2/usage-examples/bulkWrite/)
[deletemany UE](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-2/usage-examples/deleteMany/)
[count UE](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-2/usage-examples/count/)
[command UE](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-2/usage-examples/command/)
> DOCSP-34174: codewhisperer pt 2

- source/includes/usage-examples/code-snippets/deleteOne.go
- source/includes/usage-examples/code-snippets/distinct.go
- source/includes/usage-examples/code-snippets/find.go
- source/includes/usage-examples/code-snippets/findOne.go
- source/includes/usage-examples/code-snippets/insertMany.go
- source/usage-examples/deleteOne.txt
- source/usage-examples/distinct.txt
- source/usage-examples/find.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
Staging:
[deleteone](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-3/usage-examples/deleteOne/)
[distinct](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-3/usage-examples/distinct/)
[find](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-3/usage-examples/find/)
[findone](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-3/usage-examples/findOne/)
[insertmany](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-3/usage-examples/insertMany/)
> DOCSP-34174: codewhisperer pt 3

- source/fundamentals/aggregation.txt
- source/fundamentals/logging.txt
- source/includes/fundamentals/code-snippets/CRUD/upsert.go
- source/includes/fundamentals/code-snippets/aggregation.go
- source/includes/fundamentals/code-snippets/gridfs.go
- source/includes/fundamentals/code-snippets/logging.go
Staging
[upsert](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-6/fundamentals/crud/write-operations/upsert/)
[agg](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-6/fundamentals/aggregation/)
[gridfs](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-6/fundamentals/gridfs/)
[logging](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-6/fundamentals/logging/)
> DOCSP-34174: codewhisperer pt 6

- source/includes/fundamentals/code-snippets/CRUD/compoundOperations.go
- source/includes/usage-examples/code-snippets/updateOne.go
- source/includes/usage-examples/code-snippets/watch.go
- source/usage-examples/changestream.txt
- source/usage-examples/updateOne.txt
Staging:
- [updateOne](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-9/usage-examples/updateOne/)
- [watch](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-9/usage-examples/changestream/)
- [compound](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-9/fundamentals/crud/compound-operations/)
> DOCSP-34174: codewhisperer pt 9

- source/fundamentals/indexes.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-35361
Staging - https://preview-mongodbmongokart.gatsbyjs.io/golang/docsp-35361-index-fix/
> DOCSP-35361 - Update index code

- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-35622>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/v1.10/
> DOCSP-35622: EOL v1.10

- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-35622>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/v1.9/
> DOCSP-35622: EOL V1.9

- snooty.toml
JIRA - <https://jira.mongodb.org/browse/DOCSP-35622>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/v1.8/
> DOCSP-35622: EOL v1.8

- source/includes/language-compatibility-table-go.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-36575>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/golang/DOCSP-36575-bump-version/compatibility/>
> DOCSP-36575: Update minimum language version

- source/faq.txt
- source/fundamentals/aggregation.txt
- source/fundamentals/auth.txt
- source/fundamentals/bson.txt
- source/fundamentals/collations.txt
- source/fundamentals/crud/read-operations/changestream.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/fundamentals/geo.txt
- source/fundamentals/logging.txt
- source/quick-start.txt
- source/usage-examples.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-36900>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/golang/DOCSP-36900-go-atomic-typos/>
> DOCSP-36900: Quarterly tasks

- source/fundamentals/monitoring/cluster-monitoring.txt
- source/fundamentals/transactions.txt
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/golang/fix-build-errors/>
> Fix build log errors

- source/includes/fundamentals/code-snippets/CRUD/retrieve.go
JIRA - <https://jira.mongodb.org/browse/DOCS-16685>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/golang/DOCS-16685-retrieve-data-example-fix-upcoming/fundamentals/crud/read-operations/retrieve/
> DOCSP-16685: fix retrieve data fundamentals code example (upcoming)

- source/includes/fundamentals/code-snippets/CRUD/retrieve.go
Fix for v1.14 to be backported
A separate PR will be created for the master branch since the driver syntax has changed.
JIRA - <https://jira.mongodb.org/browse/DOCS-16685>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/golang/DOCS-16685-retrieve-data-example-fix/fundamentals/crud/read-operations/retrieve/
> DOCS-16685: fix retrieve data fundamentals code example

- source/includes/fundamentals/code-snippets/CRUD/changeStream.go
- source/includes/fundamentals/code-snippets/CRUD/limit.go
- source/includes/fundamentals/code-snippets/CRUD/query.go
- source/includes/fundamentals/code-snippets/CRUD/skip.go
- source/includes/fundamentals/code-snippets/CRUD/sort.go
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/golang/1.14-code-fixes/
> 1.14 Code Fixes

- source/includes/fundamentals/code-snippets/CRUD/changeStream.go
- source/includes/fundamentals/code-snippets/CRUD/limit.go
- source/includes/fundamentals/code-snippets/CRUD/query.go
- source/includes/fundamentals/code-snippets/CRUD/skip.go
- source/includes/fundamentals/code-snippets/CRUD/sort.go
> 1.14 Code Fixes (#353)

- source/fundamentals/connections/connection-guide.txt
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-38259>
Staging - no staging
> DOCSP-38259: add meta descriptions to t250

- source/compatibility.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-38773>
Staging - [Compatibility Tables](https://preview-mongodbcchomongodb.gatsbyjs.io/golang/DOCSP-38773-shared-compat-for-v1.15/compatibility/)
> DOCSP-38773: switch to shared compatibility tables

- source/index.txt
- source/quick-start.txt
- source/usage-examples.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38547
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/golang/DOCSP-38547-quickstart-title/quick-start/
> DOCSP-38547 Standardize Quick Start Title

- source/fundamentals/monitoring/cluster-monitoring.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-39064
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/golang/DOCSP-39064-description-package/fundamentals/monitoring/cluster-monitoring/
> DOCSP-39064: Remove mentions of description package

- source/usage-examples.txt
- source/usage-examples/struct-tagging.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-38893
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/golang/DOCSP-38893-usage-example-links/usage-examples/
> DOCSP-38893 Usage Example Links on UE Landing

- source/fundamentals/crud/read-operations/distinct.txt
- source/includes/fundamentals/code-snippets/CRUD/distinctValues.go
- source/includes/usage-examples/code-snippets/distinct.go
- source/quick-reference.txt
- source/usage-examples/distinct.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33504>
Staging:
- [retrieve](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-33504-distinct-cursor/fundamentals/crud/read-operations/distinct/)
- [usage ex](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-33504-distinct-cursor/usage-examples/distinct/)
- [whats new](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-33504-distinct-cursor/whats-new/#what-s-new-in-2.0)
> DOCSP-33504: distinct returns struct v2

- source/fundamentals/geo.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40849>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/golang/DOCSP-40849-vatican/fundamentals/geo/>
> DOCSP-40849: Correct Polygon representation of the Vatican

- source/fundamentals/transactions.txt
- source/includes/fundamentals/code-snippets/transaction.go
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41831>
Staging:
- [Transactions page](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-41831-txnoptions-v2/fundamentals/transactions/#session-and-transaction-options)
- [Whats new](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-41831-txnoptions-v2/whats-new/#std-label-version-2.0)
> DOCSP-41831: nested txnoptions struct

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41800>
Staging - <https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-41800-merge-options-v2/whats-new/#what-s-new-in-2.0>
> DOCSP-41800: merge options - builder pattern

- source/includes/quick-start/main.go
JIRA - https://jira.mongodb.org/browse/DOCSP-43239
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/golang/DOCSP-43239-code-scroll/quick-start/
> DOCSP-43239: Fix code scroll

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43301>
Staging - https://deploy-preview-385--docs-golang.netlify.app/whats-new/#what-s-new-in-2.0
> DOCSP-43301: canonicalonly

- snooty.toml
JIRA - [DOCSP-43974](https://jira.mongodb.org/browse/DOCSP-43974)
Staging - https://deploy-preview-395--docs-golang.netlify.app/
> EOL godoc v1.11

- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/run-command.txt
- source/fundamentals/transactions.txt
* DOCSP-42960: Removing nested components in go pages
* DOCSP-42960: Removing nested components in go pages
* DOCSP-42960: Removing nested components spacing updates
* DOCSP-42960: Removing nested components fixing rst error
(cherry picked from commit cb6466d2bbd78494a8a832481d9777f587e53123)
> Docsp 42960 nested components (#387)

- source/includes/fundamentals/code-snippets/gridfs.go
JIRA - https://jira.mongodb.org/browse/DOCSP-45268
Staging - https://deploy-preview-405--docs-golang.netlify.app/fundamentals/gridfs/#upload-with-an-output-stream
> DOCSP-45268: Close uploadStream in GridFS code

- source/fundamentals.txt
- source/fundamentals/connections.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/monitoring.txt
- source/index.txt
- source/usage-examples.txt
- source/usage-examples/find-operations.txt
- source/usage-examples/write-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44899>
Staging - <https://deploy-preview-404--docs-golang.netlify.app/>
Original: https://www.mongodb.com/docs/drivers/go/current/
> DOCSP-44899 TOC Relabel

- source/fundamentals.txt
- source/fundamentals/connections.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/monitoring.txt
- source/index.txt
- source/usage-examples.txt
- source/usage-examples/find-operations.txt
- source/usage-examples/write-operations.txt
* DOCSP-44899 TOC Relabel
* last few
* fixes
* apply standard changes
* remove documents
* last edit
* shorten on read ops
(cherry picked from commit cb99beedd3ca512e6d282c5c7442e75e31ea6f20)
JIRA - <https://jira.mongodb.org/browse/DOCSP-44899>
> [Backport v1.17] DOCSP-44899 TOC Relabel (#404)

- source/fundamentals.txt
- source/fundamentals/connections.txt
- source/fundamentals/crud.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/monitoring.txt
- source/index.txt
- source/usage-examples.txt
- source/usage-examples/find-operations.txt
- source/usage-examples/write-operations.txt
* DOCSP-44899 TOC Relabel
* last few
* fixes
* apply standard changes
* remove documents
* last edit
* shorten on read ops
(cherry picked from commit cb99beedd3ca512e6d282c5c7442e75e31ea6f20)
> [Backport v1.16] DOCSP-44899 TOC Relabel (#404)

- source/fundamentals/transactions.txt
(cherry picked from commit 7af4f27900ec057ec042fa351fc147f3865a4ce2)
> DOCSP-45871-parallel-operation-admonition

- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/embedded-arrays.txt
- source/includes/fundamentals/code-snippets/CRUD/updateArray.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-46724>
Staging - https://deploy-preview-418--docs-golang.netlify.app/fundamentals/crud/write-operations/embedded-arrays/#specify-array-elements
> DOCSP-46724: arrayfilters removal

- source/includes/quick-start/main.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-46748>
Staging - <https://deploy-preview-420--docs-golang.netlify.app/quick-start/>
> DOCSP-46748 Update Quick Start Imports to v2

- source/fundamentals/crud/write-operations/modify.txt
The Go docs don't discuss options, and this option only applies to the UpdateOne() method, so I elected to just add an admonition with the info.
JIRA - <https://jira.mongodb.org/browse/DOCSP-47275>
Staging - <https://deploy-preview-422--docs-golang.netlify.app/fundamentals/crud/write-operations/modify/>
> DOCSP-47275: Add note about UpdateOne sort functionality

- source/fundamentals/gridfs.txt
- source/includes/fundamentals/code-snippets/CRUD/retrieve.go
- source/includes/usage-examples/code-snippets/find.go
- source/includes/usage-examples/code-snippets/findOne.go
- source/includes/usage-examples/code-snippets/updateOne.go
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47800>
Staging - <https://deploy-preview-423--docs-golang.netlify.app/whats-new/>
> DOCSP-47800 Update bson primitive references

- .backportrc.json
JIRA - <https://jira.mongodb.org/browse/DOCSP-48023>
> DOCSP-48023 add versions to backporting script

- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/insertOne.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46755>
Staging - <https://deploy-preview-436--docs-golang.netlify.app/usage-examples/insertOne/>
> DOCSP-46755 Insert Docs Change Title

- source/fundamentals/crud/write-operations/upsert.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48148>
Staging - <https://deploy-preview-463--docs-golang.netlify.app/fundamentals/crud/write-operations/upsert/#example>
> [GO] Correct and clarify Upsert options example

- source/fundamentals/crud/write-operations/upsert.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48148>
> [GO] Backport: Correct and clarify Upsert options example

- source/usage-examples.txt
- source/usage-examples/changestream.txt
This will backport the following commits from `master` to `v2.0`:
> [v2.0] Merge pull request #437 from shuangela/DOCSP-46756-monitor-changes-title

- source/usage-examples.txt
- source/usage-examples/changestream.txt
This will backport the following commits from `master` to `v1.17`:
> [v1.17] Merge pull request #437 from shuangela/DOCSP-46756-monitor-changes-title

- source/usage-examples.txt
- source/usage-examples/changestream.txt
This will backport the following commits from `master` to `v1.16`:
> [v1.16] Merge pull request #437 from shuangela/DOCSP-46756-monitor-changes-title

- .github/pull_request_template.md
JIRA - <https://jira.mongodb.org/browse/DOCSP-48932>
> DOCSP-48932 Add title checklist item

- source/fundamentals/connections/connection-guide.txt
> DOCSP-48755 Docker replica sets for v<2.0

- source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47022>
[Choose a Connection Target](https://deploy-preview-519--docs-golang.netlify.app/connect/connection-targets/#connect-to-replica-sets)
> DOCSP-47022 Add link to replication manual

- source/monitoring-and-logging/monitoring.txt
Consolidates the existing 3 monitoring pages. No new content.
JIRA - <https://jira.mongodb.org/browse/DOCSP-49982>
https://deploy-preview-525--docs-golang.netlify.app/monitoring-and-logging/monitoring/#additional-information
> DOCSP-49982 Monitor Application Events

- source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47007>
https://deploy-preview-533--docs-golang.netlify.app/connect/connection-targets/#dns-service-discovery
> DOCSP-47007 DNS Service Discovery
