- source/code-snippets/updateOne.go
- source/includes/connect-guide-note.rst
- source/includes/run-example-tip.rst
- source/usage-examples.txt
- source/usage-examples/updateOne.txt
https://jira.mongodb.org/browse/DOCSP-13859
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13859-update-one-usage-ex/usage-examples/updateOne/
**TODO:** edit links to Fundamentals pages "Change a Document" and "Retrieve Data" when they are created
> DOCSP-13859: UpdateOne usage example

- source/code-snippets/updateMany.go
- source/includes/run-example-tip.rst
- source/usage-examples.txt
- source/usage-examples/updateMany.txt
https://jira.mongodb.org/browse/DOCSP-13860
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13860-updatemany-usage-ex/usage-examples/updateMany/
> DOCSP 13860: UpdateMany usage example

- source/code-snippets/find.go
- source/includes/run-example-tip.rst
- source/usage-examples/find.txt
https://jira.mongodb.org/browse/DOCSP-13856
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13856-find-usage-ex/usage-examples/find/
> DOCSP 13856: find usage example

- source/includes/usage-examples/code-snippets/deleteMany.go
- source/includes/usage-examples/code-snippets/deleteOne.go
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/find.txt
Page: Usage Examples > Delete Operations > Delete Many Documents
https://jira.mongodb.org/browse/DOCSP-13863
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13863-DeleteManyUsageExample/usage-examples/deleteMany/
> DOCSP-13863 delete many usage example

- source/compatibility.txt
- source/includes/mongodb-compatibility-table-go.rst
Updated the compatibility table to what is currently [in docs-ecosystem](https://github.com/mongodb/docs-ecosystem/blob/master/source/includes/mongodb-compatibility-table-go.rst).
https://jira.mongodb.org/browse/DOCSP-13874
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13874-CompatibilityTable/compatibility/
> DOCSP-13874 compatibility table

- source/index.txt
Added the landing page. 
Utilized the formatting of the [Node](https://github.com/mongodb/docs-node/blob/master/source/index.txt) and [Java](https://github.com/mongodb/docs-java/blob/master/source/index.txt) docs.
Note, I commented out sections (What's New, FAQ, other fundamental sections) that aren't planned to be in the first release of the docs.
https://jira.mongodb.org/browse/DOCSP-13826
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13826-LandingPage/
> DOCSP-13826 landing page

- source/fundamentals.txt
- source/fundamentals/auth.txt
Added Fundamentals > Authentication Mechanisms page
Utilized snippets from Go driver repo: https://github.com/mongodb/mongo-go-driver/blob/master/mongo/client_examples_test.go 
Based the format off of the [Node](https://docs.mongodb.com/drivers/node/fundamentals/authentication/mechanisms/) and [Java](https://docs.mongodb.com/drivers/java/sync/current/fundamentals/auth/) Auth Mechanism pages.
https://jira.mongodb.org/browse/DOCSP-13829
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13829-AuthMechanisms/fundamentals/auth/
> DOCSP-13829  authentication mechanism

- snooty.toml
- source/usage-examples.txt
Added Usage Examples landing page.
This page differs from the the Node and Java driver since we're incorporating environment variables.
https://jira.mongodb.org/browse/DOCSP-13854
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13854-UsageExamplesLanding/usage-examples/
> DOCSP-13854 usage examples landing page

- source/includes/usage-examples/code-snippets/count.go
- source/usage-examples.txt
- source/usage-examples/count.txt
Added Usage Examples > Count Documents
https://jira.mongodb.org/browse/DOCSP-13864
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13864-CountDocumentsUsageExample/usage-examples/count/
> DOCSP-13864 count documents usage example

- source/includes/usage-examples/code-snippets/replace.go
- source/usage-examples/replaceOne.txt
Added Usage Examples > Write Operations > Replace a Document page
https://jira.mongodb.org/browse/DOCSP-13861
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13861-ReplaceUsageExample/usage-examples/replaceOne/
> DOCSP-13861 replace usage example

- source/includes/usage-examples/code-snippets/insertMany.go
- source/usage-examples/insertMany.txt
- source/usage-examples/update-operations.txt
https://jira.mongodb.org/browse/DOCSP-13858
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13858/usage-examples/insertMany/
- GH link won't work until merged into master
> DOCSP-13858: add insertMany usage example

- source/usage-examples/bulkWrite.txt
- source/usage-examples/command.txt
- source/usage-examples/count.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/struct-tagging.txt
Made al the usage examples opening sentences this format: `"You can ... by using the __ method."`
https://jira.mongodb.org/browse/DOCSP-18446
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=612fb31f7dcf012930bc3613
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18446-OpeningSentence/usage-examples/
> DOCSP-18446 opening sentence

- source/fundamentals/connection.txt
- source/usage-examples.txt
This adds a ref target in the conneciton guide and links to it from the usage-example overview, replacing the todo.
https://jira.mongodb.org/browse/DOCSP-18438
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=612fd3ad7dcf012930c40704
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18438/usage-examples/
> Link to guide

- source/usage-examples/bulkWrite.txt
- source/usage-examples/command.txt
- source/usage-examples/count.txt
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/distinct.txt
- source/usage-examples/find.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/struct-tagging.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
- source/usage-examples/watch.txt
Updated all results sections to the following:
- The wording with the format:  `"After you run the preceding example, ..."`
- Link to the find pages to show how you can view the result of what was just done (all CRUD pages)
https://jira.mongodb.org/browse/DOCSP-18445
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6137e2ae7dcf0129309016b0
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18445-ResultsSection/usage-examples/
> DOCSP-18445 results sections

- source/usage-examples/bulkWrite.txt
- source/usage-examples/command.txt
- source/usage-examples/count.txt
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/distinct.txt
- source/usage-examples/find.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/struct-tagging.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
- source/usage-examples/watch.txt
Updated all example sections to the following:
- Contain an Example heading
- Move the tip box before the example statement starts
The example statements have the following formats: (omitting the parameters and method name now)
- For a list of actions: `“The following example performs ...”` 
- For non-list actions: `“The following example matches ...”`
- For insert pages: `“The following example inserts ...”`
- For watch: `“The following example opens ...”`
- For command: `“The following example retrieves ...”`
- For struct-tagging: `“The following example creates ...”`
NOTE: Only the watch page shows how to print because that showcases how to best use it
https://jira.mongodb.org/browse/DOCSP-18444
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61390773c608bec57f8cd9e6 …
> DOCSP-18444 example section

- source/fundamentals/bson.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/includes/fundamentals/code-snippets/CRUD/retrieve.go
Added the Fundamentals > CRUD > Read Operations > Retrieve page
This page focuses on the find, fineOne and aggregate functions. Because the usage example pages don't contain an explanation, a detailed explanation is provided here.
https://jira.mongodb.org/browse/DOCSP-13834
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61393ae7c608bec57f993360
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13834-CRUDRetrieve/fundamentals/crud/read-operations/retrieve/
> DOCSP-13834 crud retrieve

- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/bulkWrite.txt
- source/usage-examples/command.txt
- source/usage-examples/count.txt
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/find.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
- source/usage-examples/watch.txt
This replaces or comments out all TODO: marks. All links were checked as well. There are two known broken links that will correct themselves once the retrieve fundamentals page is merged in, which is required for the initial release.
https://jira.mongodb.org/browse/DOCSP-18440
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=613a35d7c608bec57fd498bf
This shows errors as we're linking to an as yet unmerged fundamental page.
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18440/
> Docsp 18440

- snooty.toml
- source/fundamentals/auth.txt
- source/fundamentals/bson.txt
- source/fundamentals/connection.txt
- source/fundamentals/context.txt
- source/index.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/find.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
This also removes all other uses of the URL https://pkg.go.dev/... to link to the API docs and uses the [`{+api+}`](url) constant instead. 
https://jira.mongodb.org/browse/DOCSP-18729
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61436710c608bec57fc80970
https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18729/
- Caveat: Fixing other broken links in a new PR. All changed links were checked.
> update api links to 1.7.2

- source/fundamentals/context.txt
Updated the Context page to:
- not monospace "Context"
- have an admonition in the last section about older versions of the driver
https://jira.mongodb.org/browse/DOCSP-18735
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61437e66c608bec57fd0927c
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18735/fundamentals/context/
> DOCSP-18735

- source/includes/quick-start/atlas-setup.rst
- source/includes/quick-start/main.go
- source/includes/quick-start/query-output.rst
- source/quick-start.txt
Updated the quickstart page to:
- use `panic` instead of `log.Panic`
- have the correct atlas step to copy the connection string
- use env variable instead of talking about using connection string 
- not use future tense
https://jira.mongodb.org/browse/DOCSP-18732
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=614385d5c608bec57fd338db
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18732/quick-start/
> DOCSP-18732 quick start page

- source/fundamentals/auth.txt
This removes the empty tls guide link, and shows the auth options in a list early on in the heading (and links to each one).
https://jira.mongodb.org/browse/DOCSP-18736
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6143b215c608bec57fe2cee4
https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18736/
> Docsp 18736

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/includes/fundamentals/code-snippets/CRUD/sort.go
Added the CRUD > Read Operations > Sort page.
I decided to leave out text search on this page because I think it would be better saved for the Text Search page.
Note: I found and fixed a typo in the retrieve page.
https://jira.mongodb.org/browse/DOCSP-13835
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=615cb0298670bd2731edb18b
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13835-CRUDSort/fundamentals/crud/read-operations/sort/
> DOCSP-13835 crud sort

- source/fundamentals/crud/read-operations/limit.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/includes/fundamentals/code-snippets/CRUD/limit.go
- source/includes/fundamentals/code-snippets/CRUD/skip.go
- source/includes/fundamentals/code-snippets/CRUD/sort.go
Extracted all aggregation tip boxes to be their own sections/subsections. I slightly changed the examples so the user can see a different one in each section. (It was originally the same as one of the other examples)
I also updated the wording to show the output to "After running this example, ..."
https://jira.mongodb.org/browse/DOCSP-19037
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=616497fd8670bd27318e0670
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19037-AggregationSections/fundamentals/crud/read-operations/retrieve/
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19037-AggregationSections/fundamentals/crud/read-operations/sort/
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlar …
> DOCSP-19037 updated aggregation examples

- source/fundamentals/crud/read-operations/retrieve.txt
- source/includes/fundamentals/code-snippets/CRUD/retrieve.go
Added the commonly used FindOptions to the CRUD > Read Operations page. 
Because there are about 20 options for FindOne() and Find(), I documented the commonly used ones (pages we currently/will have) and linked to the API docs for the full list. 
I also: 
- added a FindOne() example
- updated the Find() example to include options
Note: I confirmed with an engineer that I saying "to not specify ..." for default values are more accurate than `nil` for those who don't explicitly say `nil` is the default.
https://jira.mongodb.org/browse/DOCSP-18987
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6165ad088670bd273117baba
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18987-FindOptions/fundamentals/crud/read-operations/retrieve/#modify-behavior …
> DOCSP-18987 common find options

- source/fundamentals/crud.txt
- source/fundamentals/crud/compound-operations.txt
- source/includes/fundamentals/automatic-db-coll-creation.rst
- source/includes/fundamentals/code-snippets/CRUD/compoundOperations.go
Added the CRUD > Compound Operations page.
This page covers find one and: delete, update, and replace along with all their options.
https://jira.mongodb.org/browse/DOCSP-13848
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6167614c8670bd2731f3ad24
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13848-CRUDCompoundOps/fundamentals/crud/compound-operations/
> DOCSP-13848 crud compound operations

- source/fundamentals/crud/compound-operations.txt
- source/fundamentals/crud/query-document.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/fundamentals/crud/write-operations/embedded-arrays.txt
- source/includes/fundamentals/code-snippets/CRUD/updateArray.go
Added the Fundamentals > CRUD > Write Operations > Update Arrays in a Document page.
This page covers the different positional operators.
https://jira.mongodb.org/browse/DOCSP-13845
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6171e59fc13055282db5dcaa
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13845-CRUDUpdateArrays/fundamentals/crud/write-operations/embedded-arrays/
> DOCSP-13845 crud update arrays

- source/fundamentals/crud/query-document.txt
- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/bulk.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/includes/fundamentals/code-snippets/CRUD/bulkOps.go
- source/usage-examples/bulkWrite.txt
Added the Fundamentals > CRUD > Write Operations > Bulk Operations page.
This page discusses:
- The write models you can use
- The difference between ordered and unordered operations
https://jira.mongodb.org/browse/DOCSP-18350
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=617ffe5bc13055282dabb2c5
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-18350-CRUDBulkOperations/fundamentals/crud/write-operations/bulk/
> DOCSP-18350 crud bulk operations

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/project.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/fundamentals/crud/read-operations/text.txt
- source/includes/fundamentals/code-snippets/CRUD/textSearch.go
Added the Fundamentals > CRUD > Read Operations > Search Text page.
The page covers:
- Searching by a term
- Searching by a phrase
- Searching with terms excluded
- Sorting the results by relevance
https://jira.mongodb.org/browse/DOCSP-13840
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=6182c5bdc13055282d559fb4
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13840-CRUDTextSearch/fundamentals/crud/read-operations/text/
> DOCSP-13840 crud search text

- source/includes/mongodb-compatibility-table-go.rst
https://jira.mongodb.org/browse/DOCSP-19598
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=618aa4d7c13055282d6b198f
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19598-compat-5.1/compatibility/
> DOCSP-19598: update compatibility table for server 5.1

- source/fundamentals/bson.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/cursor.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/includes/fundamentals/code-snippets/CRUD/cursor.go
- source/includes/fundamentals/exhausted-cursor-definition.rst
Added the Fundamentals > CRUD > Read Operations > Access Data from a Cursor page.
This page covers all the functions you can use to access a cursors elements and ways to iterate through a cursor.
https://jira.mongodb.org/browse/DOCSP-13833
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=61aa5c2f5314b0809f18a63b
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-13833-CRUDCursor/fundamentals/crud/read-operations/cursor/
> DOCSP-13833 crud cursor

- source/quick-start.txt
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621d43609c4c7f6bfb4c9a01
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/add-ref/quick-start/
> add ref to go quickstart

- .github/workflows/checker.yml
- snooty.toml
- source/fundamentals/crud/write-operations/delete.txt
Bump API links to 1.8.4
N/A
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=622017109c4c7f6bfbe3335d
https://docs-mongodborg-staging.corp.mongodb.com/golang/docsworker-xlarge/1.8.4/
> Bump api links to 1.8.4

- source/quick-start.txt
https://jira.mongodb.org/browseDOCS-15247
[Preview](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/stennie-DOCS-15247/quick-start/#add-other-dependencies)
> DOCS-15247: Go Quick Start should mention installing godotenv

- snooty.toml
Updated api docs version to 1.7.6
JIRA - <https://jira.mongodb.org/browse/DOCSP-21977>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-21977/#api>
> DOCSP-21977 update api docs version

- source/fundamentals/auth.txt
- source/fundamentals/context.txt
- source/fundamentals/crud/compound-operations.txt
- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/distinct.txt
- source/fundamentals/crud/read-operations/limit.txt
- source/fundamentals/crud/read-operations/project.txt
- source/fundamentals/crud/read-operations/query-document.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/fundamentals/crud/read-operations/text.txt
- source/fundamentals/crud/write-operations/bulk.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/embedded-arrays.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/upsert.txt
- source/fundamentals/indexes.txt
- source/fundamentals/time-series.txt
- source/index.txt
Switched all instances of "function" to "method" to align with Go API docs. 
Updated references to collections to use dot notation
JIRA - <https://jira.mongodb.org/browse/DOCSP-21849>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-21849/fundamentals/crud/read-operations/query-document/>
> DOCSP-21849 dot notation and wording change

- snooty.toml
- source/fundamentals.txt
- source/fundamentals/stable-api.txt
- source/includes/fundamentals-sections.rst
Added the Stable API page -- based off the existing [Java](https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/stable-api/) and [Node.js](https://www.mongodb.com/docs/drivers/node/current/fundamentals/stable-api/) one.
JIRA - <https://jira.mongodb.org/browse/DOCSP-19058>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19058/fundamentals/stable-api/>
> DOCSP-19058 stable api

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/watch.txt
- source/includes/fundamentals/automatic-db-coll-creation.rst
- source/usage-examples/watch.txt
* DOCSP-18456: adding a change stream page
* fixing TOC
* code example typo
* wording fix
* more task oriented structure
* fixed punctuation
(cherry picked from commit 2ee7da991cfe7ea414cfe392258baa9a3059fed4)
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.8/>
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=62ea8851230aeb802e66f247
> DOCSP-18456: Change stream page v1.8 (#113)

- config/redirects
- snooty.toml
It looks like we missed publishing the 1.10 branch for Go. This adds the latest to master, and fills out the redirects file to be the same format as our other drivers.
This will be cherry-picked to the new 1.10 branch and the `version` in snooty will be updated.
Paired with @jordan-smith721 
JIRA - N/A
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/publish-go-1.10/)
> add go 1.10

- source/fundamentals/crud.txt
- source/fundamentals/crud/write-read-pref.txt
Ports https://github.com/mongodb/docs-golang/pull/159 to v1.10.
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.10/fundamentals/crud/write-read-pref/
> DOCSP-13849: Modify CRUD op execution - v1.10

- source/fundamentals/crud.txt
- source/fundamentals/crud/write-read-pref.txt
Ports https://github.com/mongodb/docs-golang/pull/159 to v1.9.
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.9/fundamentals/crud/write-read-pref/
> DOCSP-13849: Modify CRUD op execution - v1.9

- source/fundamentals/crud.txt
- source/fundamentals/crud/write-read-pref.txt
Ports https://github.com/mongodb/docs-golang/pull/159 to v1.8.
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.8/fundamentals/crud/write-read-pref/
> DOCSP-13849: Modify CRUD op execution - v1.8

- source/fundamentals/crud.txt
- source/fundamentals/crud/write-read-pref.txt
Ports https://github.com/mongodb/docs-golang/pull/159 to v1.7.
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.7/fundamentals/crud/write-read-pref/
> DOCSP-13849: Modify CRUD op execution - v1.7

- source/includes/usage-examples/code-snippets/findOne.go
- source/usage-examples/findOne-output.txt
- source/usage-examples/findOne.txt
- Is there another step I need to take to make sure the "fully runnable example" is correctly linked or is that updated once the new findone.go code snippet file is merged?
JIRA - <https://jira.mongodb.org/browse/DOCSP-25874>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-25874-struct-tagging-findone/usage-examples/findOne/>
> DOCSP-25874 Add Restaurant Structs to FindOne Usage Example

- source/index.txt
- source/whats-new.txt
Port https://github.com/mongodb/docs-golang/pull/185 to v1.9
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19057-whats-new-v1.9/whats-new/
> DOCSP-19057 v1.9 backport

- source/whats-new.txt
Port https://github.com/mongodb/docs-golang/pull/185 to v1.8
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-19057-whats-new-v1.8/whats-new/
> DOCSP-19057 v1.8 backport

- source/fundamentals/crud/read-operations/query-document.txt
- source/fundamentals/crud/read-operations/watch.txt
No JIRA ticket
This PR fixes the code-block rST indentation which silently failed to apply syntax highlighting for the specified language. While it's beyond expectations to review each file, to verify the syntax highlighting is applied, you'll need to individually inspect each code block with Chrome Tools for the "go" (or other) style in the code component:
Staging:
[Query Document](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/110922-fix-code-block-indentation/fundamentals/crud/read-operations/query-document/)
[Watch for Changes](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/110922-fix-code-block-indentation/fundamentals/crud/read-operations/wa …
> Fix code-block indentation

- source/fundamentals/crud/read-operations/count.txt
- source/includes/fundamentals/code-snippets/CRUD/countAndEstimate.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26435
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26435-struct-count/fundamentals/crud/read-operations/count/
> DOCSP-26435: use struct in count documents pg

- source/fundamentals/crud/read-operations/text.txt
- source/includes/fundamentals/code-snippets/CRUD/textSearch.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26444
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26444-struct-search-text/fundamentals/crud/read-operations/text/#std-label-golang-search-text
I changed the examples to fit a use case that seems more probable (searching a summary or description).
> DOCSP-26444: use struct in text search pg

- source/fundamentals/crud/read-operations/sort.txt
- source/includes/fundamentals/code-snippets/CRUD/sort.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26439
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26439-struct-sort/fundamentals/crud/read-operations/sort/
> DOCSP-26439: use struct in sort page

- source/fundamentals/crud/read-operations/limit.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/includes/fundamentals/code-snippets/CRUD/limit.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26441
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26441-struct-limit/fundamentals/crud/read-operations/limit/#std-label-golang-limit
** I also made a small fix to the sort page as I noticed a consistency issue.
> DOCSP-26441: use struct in limit pg

- source/fundamentals.txt
- source/includes/fundamentals-sections.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-26363>
Staging - 
[Fundamentals landing page
](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26363-link-to-lambda/fundamentals/)
Also, check the left nav item.
> DOCSP-26363: add link to AWS Lambda docs

- source/fundamentals/crud/read-operations/watch.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-26445
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26445-struct-watch-changes/fundamentals/crud/read-operations/watch/
> DOCSP-26445: use struct in watch for changes

- source/fundamentals/crud/write-operations.txt
- source/fundamentals/crud/write-operations/bulk.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/embedded-arrays.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/upsert.txt
- source/includes/fundamentals/code-snippets/CRUD/bulkOps.go
- source/includes/fundamentals/code-snippets/CRUD/delete.go
- source/includes/fundamentals/code-snippets/CRUD/insertOptions.go
- source/includes/fundamentals/code-snippets/CRUD/updateArray.go
- source/includes/fundamentals/code-snippets/CRUD/upsert.go
JIRA - https://jira.mongodb.org/browse/DOCSP-26447
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-26447-struct-write-ops/fundamentals/crud/write-operations/#std-label-golang-crud-write-operations
**Pages changed:**
1. bulk operations
2. insert a document
3. delete a document
4. update arrays
5. insert or update
> DOCSP-26447: use struct in write ops

- source/fundamentals/crud/read-operations/watch.txt
This will backport the following commits from `master` to `v1.10`:
- [DOCSP-22507: changestream pre and post images (#228)](https://github.com/mongodb/docs-golang/pull/228)
> [v1.10] DOCSP-22507: changestream pre and post images (#228)

- source/fundamentals/crud/read-operations/watch.txt
This will backport the following commits from `master` to `v1.11`:
- [DOCSP-22507: changestream pre and post images (#228)](https://github.com/mongodb/docs-golang/pull/228)
> [v1.11] DOCSP-22507: changestream pre and post images (#228)

- .backportrc.json
- source/fundamentals/bson.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27504
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-27504-refer-as-type/fundamentals/bson/
> DOCSP-27504: change Go value references to Go type + backport file

- .backportrc.json
- source/fundamentals/bson.txt
- source/whats-new.txt
This will backport the following commits from `master` to `v1.11`:
> [v1.11] change Go value to Go type + backport file (#231)

- .backportrc.json
- source/fundamentals/bson.txt
- source/whats-new.txt
This will backport the following commits from `master` to `v1.9`:
> [v1.9] change Go value to Go type + backport file (#231)

- .backportrc.json
- source/fundamentals/bson.txt
- source/whats-new.txt
This will backport the following commits from `master` to `v1.8`:
> [v1.8] change Go value to Go type + backport file (#231)

- .backportrc.json
- source/fundamentals/bson.txt
- source/whats-new.txt
This will backport the following commits from `master` to `v1.7`:
> [v1.7] change Go value to Go type + backport file (#231)

- .backportrc.json
- source/fundamentals/bson.txt
- source/whats-new.txt
This will backport the following commits from `master` to `v1.10`:
> [v1.10] change Go value to Go type + backport file (#231)

- source/fundamentals/crud/read-operations/count.txt
This will backport the following commits from `master` to `v1.9`:
- [DOCSP-27258 countDocuments collScan note (#245)](https://github.com/mongodb/docs-golang/pull/245)
> [v1.9] DOCSP-27258 countDocuments collScan note (#245)

- source/fundamentals/crud/read-operations/count.txt
This will backport the following commits from `master` to `v1.8`:
- [DOCSP-27258 countDocuments collScan note (#245)](https://github.com/mongodb/docs-golang/pull/245)
> [v1.8] DOCSP-27258 countDocuments collScan note (#245)

- source/fundamentals/crud/read-operations/count.txt
This will backport the following commits from `master` to `v1.7`:
- [DOCSP-27258 countDocuments collScan note (#245)](https://github.com/mongodb/docs-golang/pull/245)
> [v1.7] DOCSP-27258 countDocuments collScan note (#245)

- source/fundamentals/crud/read-operations/project.txt
- source/fundamentals/crud/read-operations/sort.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-27577
Staging - [Sort](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-27577-compound-method-lang/fundamentals/crud/read-operations/sort/) | [Project](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-27577-compound-method-lang/fundamentals/crud/read-operations/project/)
- [n/a] Did you run a spell-check?
- [n/a] Did you run a grammar-check?
- [n/a] Are all the links working?
> DOCSP-27577: refer to compound operations correctly

- source/index.txt
- source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-29485
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-29485-remove-releasenotes-item/whats-new/)
> DOCSP-29485: remove release notes link from nav, move link to WN

- source/whats-new.txt
JIRA - [DOCSP-29541](https://jira.mongodb.org/browse/DOCSP-29541)
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-29541-newclient-deprecated/whats-new/#what-s-new-in-1.12
> DOCSP-29541: newclient and connect deprecation notice

- source/fundamentals/geo.txt
Backport #264 to v1.11
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/v1.11/fundamentals/geo/#geospatial-indexes
> DOCSP-30083 : Backport fix geospatial typo (#264 to v1.11)

- source/fundamentals/collations.txt
- source/fundamentals/crud/read-operations/count.txt
- source/fundamentals/crud/read-operations/query-document.txt
- source/fundamentals/crud/read-operations/text.txt
- source/fundamentals/crud/write-operations/change-a-document.txt
- source/includes/fundamentals-sections.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-30082>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-30082-replace-doc-directives/fundamentals/crud/read-operations/count/>
replaced :doc: with :ref: in 5 locations/ turned unimplemented :doc: comments into updated, implemented documentation.
> DOCSP-30082: Replace doc directives

- source/quick-reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-29902>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-29902-Revise-quick-reference-examples/quick-reference/)
> Docsp 29902 revise quick reference examples

- source/fundamentals/bson.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30927>
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-30927-Work-With-BSON-options/fundamentals/bson/)
> Docsp 30927 work with bson options

- source/whats-new.txt
[Version 1.11.8 has been retracted](https://github.com/mongodb/mongo-go-driver/releases/tag/v1.11.8)
JIRA - https://jira.mongodb.org/browse/DOCSP-31832
Staging - https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/docsp-31832-version-update/whats-new/#what-s-new-in-1.11
> DOCSP-31832 - 1.11.8 retraction

- source/compatibility.txt
- source/fundamentals/connection.txt
- source/includes/lifecycle-schedule-callout.rst
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-30911>
Staging - https://preview-mongodbcchomongodb.gatsbyjs.io/rust/DOCSP-30911-server-support/compatibility/#mongodb-compatibility
> DOCSP-30911: Add server lifecycle support callout

- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/write-operations.txt
- source/usage-examples/find-operations.txt
- source/usage-examples/write-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-24435>
Staging - 
https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-24435-meta/usage-examples/
> DOCSP-24435: Add meta descriptions

- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/includes/fundamentals/code-snippets/CRUD/retrieve.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-32693>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/golang/docsworker-xlarge/DOCSP-32693-find-by-id/fundamentals/crud/read-operations/retrieve/>
> DOCSP-32693: FindOne by ObjectId

- config/redirects
To observe the current behavior:
1) Visit https://www.mongodb.com/docs/drivers/go/current/fundamentals/logging/
2) Use the version selector to switch to version v1.9. This should redirect to the landing page, but instead produces a 404.
JIRA - None
Staging - None
> fix version redirects

- source/fundamentals.txt
- source/fundamentals/network-compression.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-33282>
Staging - <https://preview-mongodbnorareidy.gatsbyjs.io/golang/DOCSP-33282-network-compression/fundamentals/network-compression/>
> DOCSP-33282: Network compression

- source/includes/fact-environments.rst
- source/includes/fundamentals/code-snippets/CRUD/limit.go
- source/includes/fundamentals/code-snippets/CRUD/projection.go
- source/includes/fundamentals/code-snippets/CRUD/query.go
- source/includes/fundamentals/code-snippets/CRUD/retrieve.go
- source/index.txt
Staging:
[specify query](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-1/fundamentals/crud/read-operations/query-document/)
[retrieve](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-1/fundamentals/crud/read-operations/retrieve/)
[limit](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-1/fundamentals/crud/read-operations/limit/)
[project](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-1/fundamentals/crud/read-operations/limit/)
> DOCSP-34174: codewhisperer pt 1

- source/fundamentals/time-series.txt
- source/fundamentals/transactions.txt
- source/includes/fundamentals/code-snippets/srv.go
- source/includes/fundamentals/code-snippets/timeSeries.go
- source/includes/fundamentals/code-snippets/timeSeriesRunCommand.go
- source/includes/fundamentals/code-snippets/tls.go
- source/includes/fundamentals/code-snippets/transaction.go
Staging
[timeseries](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-4/fundamentals/time-series/#example)
[transaction](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-4/fundamentals/transactions/#example)
[TLS](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-4/fundamentals/connections/tls/#example)
[connection guide](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-4/fundamentals/connections/connection-guide/#connection-uri)
> DOCSP-34174: codewhisperer pt 4

- source/includes/fundamentals/code-snippets/CRUD/runCommand.go
- source/includes/fundamentals/code-snippets/CRUD/skip.go
- source/includes/fundamentals/code-snippets/CRUD/sort.go
- source/includes/fundamentals/code-snippets/CRUD/textSearch.go
- source/includes/fundamentals/code-snippets/CRUD/updateArray.go
Staging -
[textsearch](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-5/fundamentals/crud/read-operations/text/)
[skip](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-5/fundamentals/crud/read-operations/skip/)
[sort](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-5/fundamentals/crud/read-operations/sort/)
[command](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-5/fundamentals/run-command/#example)
[arrays](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34174-codewhisperer-5/fundamentals/crud/write-operations/embedded-arr …
> DOCSP-34174: codewhisperer pt 5

- source/fundamentals/bson.txt
Changing the `OmitZeroStruct` option to `NilSliceAsEmpty` to match with the description of the option in the narrative.
JIRA - https://jira.mongodb.org/browse/DOCSP-35287
Staging - https://preview-mongodbjordansmith721.gatsbyjs.io/golang/bson-option-typo/fundamentals/bson/#bson-options
> DOCSP-35287 Fix incorrect BSON option

- source/fundamentals/bson.txt
(cherry picked from commit bacbc5f093469027be55536fa7c4a446e3f1f705)
> DOCSP-35287 Fix incorrect BSON option (#329)

- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-34822>
[Staging](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-34822-commitTXN-idempotency/fundamentals/transactions/#methods:~:text=Retrying%20a%20Transaction)
> DOCSP-34822: commitTxn is idempotent

- source/fundamentals/monitoring/command-monitoring.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-35814>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-35814-serverconnID-field-rm/whats-new/#std-label-version-2.0
> DOCSP-35814: renames connid64 type, removes old field in v2

- source/fundamentals/aggregation.txt
- source/fundamentals/crud/write-operations/embedded-arrays.txt
- source/includes/fundamentals/code-snippets/CRUD/distinctValues.go
- source/includes/fundamentals/code-snippets/CRUD/insertOptions.go
- source/includes/fundamentals/code-snippets/aggregation.go
- source/includes/fundamentals/code-snippets/gridfs.go
- source/includes/fundamentals/code-snippets/srv.go
- source/includes/fundamentals/code-snippets/timeSeriesRunCommand.go
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/golang/code-file-fixes/
> Code file fixes

- source/fundamentals/transactions.txt
- source/includes/fundamentals/code-snippets/transaction.go
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-38345>
Staging
- [whats new](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-38345-session-struct/whats-new/#std-label-version-2.0)
- [txn page](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-38345-session-struct/fundamentals/transactions/#example)
> DOCSP-38345: session converted to struct

- source/includes/usage-examples/code-snippets/find.go
- source/usage-examples/find.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-40206>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-40206-cursor-all-usageex/usage-examples/find/#example
> DOCSP-40206: find usageex edit

- source/fundamentals/indexes.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41551>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-41551-dropone-return-type/fundamentals/indexes/#remove-an-index
[whats new
](https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-41551-dropone-return-type/whats-new/#what-s-new-in-2.0)
> DOCSP-41551: dropone() return type

- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43182>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/golang/DOCSP-43182-v2-descriptive/whats-new/#what-s-new-in-2.0
> DOCSP-43182: add description to go v2 intro

- source/fundamentals/enterprise-auth.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-43664>
Staging - https://deploy-preview-383--docs-golang.netlify.app/whats-new/#what-s-new-in-1.17
> DOCSP-43664: v1.17 release (whats new)

- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/run-command.txt
- source/fundamentals/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42960>
Staging - Run a command <https://deploy-preview-387--docs-golang.netlify.app/fundamentals/run-command/>
Staging - Transactions <https://deploy-preview-387--docs-golang.netlify.app/fundamentals/transactions/>
Staging - Retrieve <https://deploy-preview-387--docs-golang.netlify.app/fundamentals/crud/read-operations/retrieve/#modify-behavior>
> Docsp 42960 nested components

- source/fundamentals/crud/read-operations/retrieve.txt
- source/fundamentals/run-command.txt
- source/fundamentals/transactions.txt
* DOCSP-42960: Removing nested components in go pages
* DOCSP-42960: Removing nested components in go pages
* DOCSP-42960: Removing nested components spacing updates
* DOCSP-42960: Removing nested components fixing rst error
(cherry picked from commit cb6466d2bbd78494a8a832481d9777f587e53123)
> Docsp 42960 nested components (#387)

- source/compatibility.txt
- source/fundamentals/encrypt-fields.txt
- source/includes/include-fixes/compatibility-table-legend.rst
- source/includes/include-fixes/encrypt-fields.rst
- source/includes/include-fixes/language-compatibility-table-go.rst
- source/includes/include-fixes/lifecycle-schedule-callout.rst
- source/includes/include-fixes/mongodb-compatibility-table-go.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-45451>
Staging:
- [Compatibility](https://deploy-preview-406--docs-golang.netlify.app/compatibility/)
- [In-Use Encryption](https://deploy-preview-406--docs-golang.netlify.app/fundamentals/encrypt-fields/)
> Fix sharedinclude content in current

- config/redirects
- snooty.toml
- source/includes/mongodb-compatibility-table-go.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-46247>
Compatibility - <https://deploy-preview-415--docs-golang.netlify.app/compatibility/>
> DOCSP-46257 Go release v2.0

- source/usage-examples.txt
- source/usage-examples/count.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46753>
Staging - <https://deploy-preview-426--docs-golang.netlify.app/usage-examples/count/>
> DOCSP-46753 Change Go driver Count Documents duplicate title

- source/usage-examples.txt
- source/usage-examples/count.txt
This will backport the following commits from `master` to `v2.0`:
> [v2.0] Merge pull request #426 from shuangela/DOCSP-46753-go-driver-count-docs-duplicate

- source/usage-examples.txt
- source/usage-examples/count.txt
This will backport the following commits from `master` to `v1.17`:
> [v1.17] Merge pull request #426 from shuangela/DOCSP-46753-go-driver-count-docs-duplicate

- source/usage-examples.txt
- source/usage-examples/count.txt
This will backport the following commits from `master` to `v1.16`:
> [v1.16] Merge pull request #426 from shuangela/DOCSP-46753-go-driver-count-docs-duplicate

- source/usage-examples.txt
- source/usage-examples/count.txt
This will backport the following commits from `master` to `v1.15`:
> [v1.15] Merge pull request #426 from shuangela/DOCSP-46753-go-driver-count-docs-duplicate

- source/usage-examples.txt
- source/usage-examples/count.txt
This will backport the following commits from `master` to `v1.14`:
> [v1.14] Merge pull request #426 from shuangela/DOCSP-46753-go-driver-count-docs-duplicate

- source/usage-examples.txt
- source/usage-examples/count.txt
This will backport the following commits from `master` to `v1.12`:
> [v1.12] Merge pull request #426 from shuangela/DOCSP-46753-go-driver-count-docs-duplicate

- source/usage-examples.txt
- source/usage-examples/count.txt
This will backport the following commits from `master` to `v1.13`:
> [v1.13] Merge pull request #426 from shuangela/DOCSP-46753-go-driver-count-docs-duplicate

- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/insertOne.txt
This will backport the following commits from `master` to `v2.0`:
> [v2.0] Merge pull request #436 from shuangela/DOCSP-46755-insert-docs-go-change-title

- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/insertOne.txt
This will backport the following commits from `master` to `v1.17`:
> [v1.17] Merge pull request #436 from shuangela/DOCSP-46755-insert-docs-go-change-title

- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/insertOne.txt
This will backport the following commits from `master` to `v1.16`:
> [v1.16] Merge pull request #436 from shuangela/DOCSP-46755-insert-docs-go-change-title

- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/insertOne.txt
This will backport the following commits from `master` to `v1.15`:
> [v1.15] Merge pull request #436 from shuangela/DOCSP-46755-insert-docs-go-change-title

- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/insertOne.txt
This will backport the following commits from `master` to `v1.14`:
> [v1.14] Merge pull request #436 from shuangela/DOCSP-46755-insert-docs-go-change-title

- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/insertOne.txt
This will backport the following commits from `master` to `v1.13`:
> [v1.13] Merge pull request #436 from shuangela/DOCSP-46755-insert-docs-go-change-title

- source/fundamentals/crud/write-operations/insert.txt
- source/usage-examples/insertOne.txt
This will backport the following commits from `master` to `v1.12`:
> [v1.12] Merge pull request #436 from shuangela/DOCSP-46755-insert-docs-go-change-title

- source/usage-examples.txt
- source/usage-examples/write-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46761>
Staging - <https://deploy-preview-439--docs-golang.netlify.app/usage-examples/write-operations/>
> DOCSP-46761 Change write operations title

- source/usage-examples.txt
- source/usage-examples/write-operations.txt
This will backport the following commits from `master` to `v2.0`:
> [v2.0] Merge pull request #439 from shuangela/DOCSP-46761-write-operations-change-title

- source/usage-examples.txt
- source/usage-examples/write-operations.txt
This will backport the following commits from `master` to `v1.17`:
> [v1.17] Merge pull request #439 from shuangela/DOCSP-46761-write-operations-change-title

- source/usage-examples.txt
- source/usage-examples/write-operations.txt
This will backport the following commits from `master` to `v1.16`:
> [v1.16] Merge pull request #439 from shuangela/DOCSP-46761-write-operations-change-title

- source/usage-examples.txt
- source/usage-examples/write-operations.txt
This will backport the following commits from `master` to `v1.15`:
> [v1.15] Merge pull request #439 from shuangela/DOCSP-46761-write-operations-change-title

- source/usage-examples.txt
- source/usage-examples/write-operations.txt
This will backport the following commits from `master` to `v1.14`:
> [v1.14] Merge pull request #439 from shuangela/DOCSP-46761-write-operations-change-title

- source/usage-examples.txt
- source/usage-examples/write-operations.txt
This will backport the following commits from `master` to `v1.13`:
> [v1.13] Merge pull request #439 from shuangela/DOCSP-46761-write-operations-change-title

- source/usage-examples.txt
- source/usage-examples/changestream.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46756>
Staging - <https://deploy-preview-437--docs-golang.netlify.app/fundamentals/crud/read-operations/changestream/>
> DOCSP-46756 Monitor Changes change duplicate title

- source/usage-examples.txt
- source/usage-examples/changestream.txt
This will backport the following commits from `master` to `v1.14`:
> [v1.14] Merge pull request #437 from shuangela/DOCSP-46756-monitor-changes-title

- source/usage-examples.txt
- source/usage-examples/changestream.txt
This will backport the following commits from `master` to `v1.13`:
> [v1.13] Merge pull request #437 from shuangela/DOCSP-46756-monitor-changes-title

- source/fundamentals/indexes.txt
- source/includes/fundamentals/code-snippets/indexes/atlasVectorSearch.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-47797>
Staging - <https://deploy-preview-462--docs-golang.netlify.app/fundamentals/indexes/#atlas-search-and-vector-search-indexes>
> DOCSP-47797 Add VS and AVS to indexes page

- source/fundamentals/enterprise-auth.txt
- source/includes/authentication/kubernetes.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-48312>
Staging - <https://deploy-preview-476--docs-golang.netlify.app/fundamentals/enterprise-auth/#kubernetes>
> DOCSP-48312 Kubernetes Auth Support

- source/fundamentals/bson.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48090>
Staging - <https://deploy-preview-477--docs-golang.netlify.app/fundamentals/bson/>
> DOCSP-48090 OmitEmpty global flag

- source/connection-troubleshooting.txt
- source/usage-examples.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48712>
Staging - <https://deploy-preview-480--docs-golang.netlify.app/connection-troubleshooting/>
<https://deploy-preview-480--docs-golang.netlify.app/usage-examples/>
> DOCSP-48712 edit for proper user/pw info

- source/fundamentals/auth.txt
- source/fundamentals/crud/read-operations.txt
- source/fundamentals/crud/read-operations/retrieve.txt
- source/usage-examples/count.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48942>
Staging - https://deploy-preview-484--docs-golang.netlify.app/fundamentals/auth/#mongodb-aws
> DOCSP-48942: add ARN env var assignment

- source/fundamentals/connections/connection-guide.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48755>
Staging - <https://deploy-preview-490--docs-golang.netlify.app/fundamentals/connections/connection-guide/#direct-connection>
> DOCSP-48755 Add connect to replica set in Docker note

- source/fundamentals/crud/compound-operations.txt
- source/fundamentals/crud/read-operations/skip.txt
- source/fundamentals/crud/read-operations/sort.txt
- source/fundamentals/crud/write-operations/bulk.txt
- source/fundamentals/crud/write-operations/delete.txt
- source/fundamentals/crud/write-operations/insert.txt
- source/fundamentals/crud/write-operations/modify.txt
- source/fundamentals/indexes.txt
- source/fundamentals/stable-api.txt
- source/quick-reference.txt
- source/usage-examples/command.txt
- source/usage-examples/deleteMany.txt
- source/usage-examples/deleteOne.txt
- source/usage-examples/findOne.txt
- source/usage-examples/insertMany.txt
- source/usage-examples/insertOne.txt
- source/usage-examples/replaceOne.txt
- source/usage-examples/updateMany.txt
- source/usage-examples/updateOne.txt
- source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49699>
Staging - https://deploy-preview-496--docs-golang.netlify.app/fundamentals/crud/compound-operations/
> DOCSP-49699: compound ops page typo fix

- source/includes/quick-start/atlas-setup.rst
I decided to remove the screenshots since I don't know that they add much, and they're dependent on non-dbx work.
JIRA - <https://jira.mongodb.org/browse/DOCSP-49650>
> [Go] Remove screenshots

- source/databases-collections.txt
- source/includes/databases-collections.go
- source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47020>
- [Databases and Collections](https://deploy-preview-504--docs-golang.netlify.app/databases-collections/)
- [Index](https://deploy-preview-504--docs-golang.netlify.app/)
> DOCSP-47020 Databases and collections

- source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49972>
[connect/connection-targets](https://deploy-preview-514--docs-golang.netlify.app/connect/connection-targets/)
> DOCSP-49972 Choose a Connection Target

- source/atlas-search.txt
- source/includes/fundamentals/code-snippets/indexes/atlasSearch.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-49622>
https://deploy-preview-508--docs-golang.netlify.app/atlas-search/
> DOCSP-49622 Atlas Search

- snooty.toml
- source/crud/query/retrieve.txt
- source/crud/update.txt
- source/crud/update/upsert.txt
- source/includes/usage-examples/code-snippets/updateMany.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-49976>
https://deploy-preview-517--docs-golang.netlify.app/crud/update/
https://deploy-preview-517--docs-golang.netlify.app/crud/query/retrieve/
> DOCSP-49976 Update Documents

- source/archive-reference-files/fundamentals/crud/read-operations/changestream.txt
- source/archive-reference-files/fundamentals/crud/read-operations/count.txt
- source/archive-reference-files/fundamentals/crud/read-operations/limit.txt
- source/archive-reference-files/fundamentals/crud/read-operations/skip.txt
- source/archive-reference-files/fundamentals/crud/read-operations/sort.txt
- source/crud/insert.txt
- source/crud/query.txt
- source/crud/query/text.txt
- source/reference/quick-reference.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-50493>
> DOCSP-50493: quick reference cleanup

- source/reference/release-notes.txt
- source/reference/upgrade.txt
JIRA - <https://github.com/stephmarie17/docs-golang/pull/new/docsp-49623-upgradeMajorVersions>
[Upgrade Versions](https://deploy-preview-531--docs-golang.netlify.app/reference/upgrade/)
[Release Notes](https://deploy-preview-531--docs-golang.netlify.app/reference/release-notes/)
> DOCSP-49623 Upgrade versions

- source/crud/update.txt
- source/includes/usage-examples/code-snippets/updateMany.go
- source/includes/usage-examples/code-snippets/updateManyBson.go
- source/includes/usage-examples/code-snippets/updateOne.go
- source/includes/usage-examples/code-snippets/updateOneBson.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-51817>
[Update One](https://deploy-preview-540--docs-golang.netlify.app/crud/update/#update-a-document-example--full-file)
> DOCSP-51817 Move update usage examples

- source/archive-reference-files/usage-examples/command.txt
- source/includes/usage-examples/code-snippets/command.go
- source/run-command.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-51824>
https://deploy-preview-545--docs-golang.netlify.app/run-command/#run-a-command-example--full-file
> DOCSP-51824 Standardize Run a Command usage ex

- source/crud/bulk.txt
- source/includes/usage-examples/code-snippets/bulk.go
JIRA - <https://jira.mongodb.org/browse/DOCSP-51820>
[Bulk Write Operations](https://deploy-preview-548--docs-golang.netlify.app/crud/bulk/#bulk-operation-example--full-file)
> DOCSP-51820 Move and standardize bulk operations usage example

- source/fundamentals/bson.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-51805>
<li><a href=https://deploy-preview-549--docs-golang.netlify.app/fundamentals/bson>fundamentals/bson</a></li>
> DOCSP-51805-bson-raw
